-- Active clients
SELECT id, name, email FROM client WHERE active = TRUE;

-- Check reservations for a specific client
SELECT r.id AS reservation_id, r.reservation_datetime, r.status, room.name AS room_name
FROM reservation r JOIN room ON r.room_id = room.id
WHERE r.client_id = 1; -- You can replace the client id

-- List all available rooms
SELECT id, name, capacity, location FROM room 
WHERE availability = TRUE;

-- Equipment available in a specific room
SELECT e.name AS equipment_name, room.name AS room_name FROM equipment e
JOIN room ON e.room_id = room.id WHERE room.id = 1; -- You can replace the room id

-- Count reservations by status
SELECT status, COUNT(*) AS total FROM reservation GROUP BY status;

-- Reports generated by a specific admin
SELECT r.id AS report_id, r.generation_date, r.data FROM report r
WHERE r.admin_id = 1; -- You can replace the admin id

-- Reservations associated with a report
SELECT rr.report_id, res.id AS reservation_id, res.reservation_datetime, res.status
FROM report_reservation rr JOIN reservation res ON rr.reservation_id = res.id
WHERE rr.report_id = 1; -- You can replace the report id

-- Check if a room is available for a specific time
SELECT r.id AS reservation_id, r.reservation_datetime, r.status 
FROM reservation r
WHERE r.room_id = 1 -- You can replace the room id
AND r.reservation_datetime = '2025-01-15 09:00:00'; -- You can replace the datetime

-- List all future reservations
SELECT r.id AS reservation_id, r.reservation_datetime, r.status, c.name AS client_name, room.name AS room_name
FROM reservation r JOIN client c ON r.client_id = c.id JOIN room ON r.room_id = room.id
WHERE r.reservation_datetime > NOW();

-- Room occupancy report
SELECT room.name AS room_name, COUNT(r.id) AS total_reservations
FROM room LEFT JOIN reservation r ON room.id = r.room_id GROUP BY room.name
ORDER BY total_reservations DESC;